name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  restore_caches:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
      - name: Cache Docker images
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
  
  lint_and_test:
    needs: restore_caches
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Black check
        run: black --check src
      - name: Flake8
        run: flake8 --max-complexity=10 src scripts
      - name: MarkdownLint
        run: markdownlint readme.md
      - name: Pytest
        run: pytest --maxfail=1 --disable-warnings --cov=src --cov-fail-under=90
        env:
          GIT_LARGE_REPO: ${{ secrets.GIT_LARGE_REPO || 'false' }}
  
  build_report:
    needs: lint_and_test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run report builder
        run: scripts/make_report.sh
